Traceback (most recent call last):
  File "/data/app/alert/app.py", line 12, in <module>
    from processor import zabbix_alert,prometheus_alert,kibana_alert
  File "/data/app/alert/processor.py", line 18, in <module>
    Today = datetime.datetime.today()
NameError: name 'datetime' is not defined
Traceback (most recent call last):
  File "/data/app/alert/app.py", line 12, in <module>
    from processor import zabbix_alert,prometheus_alert,kibana_alert
  File "/data/app/alert/processor.py", line 18, in <module>
    Today = datetime.datetime.today()
NameError: name 'datetime' is not defined
Traceback (most recent call last):
  File "/data/app/alert/app.py", line 12, in <module>
    from processor import zabbix_alert,prometheus_alert,kibana_alert
  File "/data/app/alert/processor.py", line 18, in <module>
    Today = datetime.datetime.today()
NameError: name 'datetime' is not defined
Traceback (most recent call last):
  File "/data/app/alert/app.py", line 12, in <module>
    from processor import zabbix_alert,prometheus_alert,kibana_alert
  File "/data/app/alert/processor.py", line 18, in <module>
    Today = datetime.datetime.today()
NameError: name 'datetime' is not defined
